### ISSUE TITLE
KeyError: 'open_rack_cell_glassback'

### ISSUE THREAD

**Issue by kurt-rhee** [toddkarin/vocmax#1]
Hello, 

Thank you for creating this package, it's wonderful.  I am having an issue where: 

`pvlib.temperature.TEMPERATURE_MODEL_PARAMETERS['sapm']` 
[line 1022 in main.py]

only gives:

`
{'open_rack_glass_glass': {'a': -3.47, 'b': -0.0594, 'deltaT': 3},
 'close_mount_glass_glass': {'a': -2.98, 'b': -0.0471, 'deltaT': 1},
 'open_rack_glass_polymer': {'a': -3.56, 'b': -0.075, 'deltaT': 3},
 'insulated_back_glass_polymer': {'a': -2.81, 'b': -0.0455, 'deltaT': 0}}
`

and therefore I get a KeyError for open_rack_cell_glassback. Perhaps the solution is to change the default value for 'named_model' to one of the available dictionary keys.

Thank you for your assistance,

Kurt

**Comment by toddkarin** [comment]
Thanks for this! I forgot to update the example file in the readme. It's fixed now. (pvlib changed their labeling of the temperature model parameters). Let me know if you still have issues.

**Comment by kurt-rhee** [comment]
Thanks @toddkarin
