### ISSUE TITLE
AttributeError: module 'vocmax' has no attribute ashrae get_data_at_loc

### ISSUE THREAD

**Issue by kurt-rhee** [toddkarin/vocmax#2]
Hello, 

The following function does not have a get_data_at_loc function.  I searched within Main.py and found there was a similar sounding functions such as "ashrae_get_design_conditions_at_loc" and ashrae_get_data, through ashrae_get_data was commented out.

`
# Get ASHRAE design temperature:
ashrae = vocmax.ashrae_get_data_at_loc(lat,lon)
`
[Example line 255]

Thank you again for your help

**Comment by toddkarin** [comment]
There is a function ashrae_get_design_conditions_at_loc in main.py. Could you try updating to the latest version of vocmax and trying again?

**Comment by kurt-rhee** [comment]
Hello Todd, 

I see that the latest version on PyPi is 0.0.21 released July 21st, 2020.  This is the version I have installed.  
https://pypi.org/project/vocmax/

I do also see though that the example script has also changed, I will see if I can get the program to work with the new example script.  I will test now and close it out of things work as expected.

Thank you for your help.

**Comment by kurt-rhee** [comment]
It works! Thank you
