### ISSUE TITLE
Function "get_weather_data" is not working

### ISSUE THREAD

**Issue by kurt-rhee** [toddkarin/vocmax#3]
Hello, 

I tried to run get_weather_data today but got the following error:

![image](https://user-images.githubusercontent.com/33131958/92852872-0e666880-f3a4-11ea-98f9-4d7e2f38ac24.png)

I went into the vocmax folder in main and tried copying the url into my browser url bar.  This successfully retrieved a CSV file so I know that the lat, lon and api_key are correct.  

latitude = 33.38
longitude = -115.38

Thank you for your help.

**Comment by kurt-rhee** [comment]
It might be a http: https: issue

**Comment by kurt-rhee** [comment]
I tried chanign to https and now I'm having a different error

![image](https://user-images.githubusercontent.com/33131958/92859038-9dc34a00-f3ab-11ea-9004-ff3c01ec2cab.png)

**Comment by toddkarin** [comment]
My plan in the future is to use the pvlib version of a similar function: https://pvlib-python.readthedocs.io/en/latest/generated/pvlib.iotools.get_psm3.html

For fixing this bug, can you try checking what the `temperature` input is?

**Comment by kurt-rhee** [comment]
![image](https://user-images.githubusercontent.com/33131958/93779876-4b203400-fbdc-11ea-8218-9779b3bf9849.png)

Also getting this error.

**Comment by kurt-rhee** [comment]
Looks like changing to https fixes the original issue.  The other problem was importing vocmax changes the relative lookup path for the ashrae xlsx file.  Rewriting the imports to use relative paths fixed the problem.
