### ISSUE TITLE
Question:  Backside irradiance fraction vs. albedo

### ISSUE THREAD

**Issue by kurt-rhee** [toddkarin/vocmax#4]
![image](https://user-images.githubusercontent.com/33131958/93106607-57007900-f665-11ea-9aeb-45b7994d27ec.png)

Is the albedo value ignored when the bifacial model is proportional?

**Comment by toddkarin** [comment]
Good question, the albedo is still used to get the front plane-of-array irradiance using [pvlib.irradiance.get_total_irradiance](https://pvlib-python.readthedocs.io/en/stable/generated/pvlib.irradiance.get_total_irradiance.html)

**Comment by kurt-rhee** [comment]
Understood thank you!
