### ISSUE TITLE
pvtools website seems broken

### ISSUE THREAD

**Issue by mikofski** [toddkarin/vocmax#8]
if I visit https://pvtools.herokuapp.com/ this is what I see:
![image](https://user-images.githubusercontent.com/1385621/133701756-1fb922c8-baa2-4800-8e17-548e3bd24bda.png)

**Comment by acarchedi1** [comment]
i am also looking to use this tool. same error.

**Comment by X-Chen97** [comment]
Hi everyone!

Pvtools website was down for a few days. We apologize for the inconvenience. Now the issues are fixed. You can visit https://pvtools.lbl.gov/ to use our tools. In the meanwhile, the domain "www.pvtools.lbl.gov" is still down. I will continue fixing the problems.

Thanks
